# This docker-compose.yml file is used to build and test quickly
# a specific version of Dolibarr
#
# Before build, define the variable DOLI_VERSION as following:
# $ export DOLI_VERSION=4.0.4
# And then, you can run :
# $ docker-compose up
#
# More information about Docker-compose : https://docs.docker.com/compose/

version: "3.8"


services:
    db:
        image: yobasystems/alpine-mariadb
        env_file: .env
        volumes:
            - ./.volumes/mariadb:/var/lib/mysql
        healthcheck:
            test: ["CMD-SHELL", "mysqladmin ping -p$$MYSQL_ROOT_PASSWORD | grep 'mysqld is alive' || exit 1"]
            interval: 2s
            retries: 120

    dolibarr:
        build:
            context: .
        image: easya
        volumes:
            - ./.volumes/dolibarr/documents:/var/www/documents
            - ./.volumes/dolibarr/html:/var/www/html
        depends_on:
            db:
                condition: service_healthy
        env_file: .env
        healthcheck:
            interval: 2s
            retries: 120

    cron:
        build:
            context: .
        image: easya
        volumes:
            - ./.volumes/dolibarr/documents:/var/www/documents
            - ./.volumes/dolibarr/html:/var/www/html
        env_file: .env
        command: cron.sh
        depends_on:
            dolibarr:
                condition: service_healthy

    web:
        image: nginx
        volumes:
            - ./nginx.conf:/etc/nginx/nginx.conf:ro
            - /etc/localtime:/etc/localtime:ro
            - ./.volumes/dolibarr/documents:/var/www/documents:ro
            - ./.volumes/dolibarr/html:/var/www/html:ro
        depends_on:
            dolibarr:
                condition: service_healthy
        ports:
            - 80:80
